config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#about'
  get 'static_pages/about'
  get 'static_pages/weatherstation'
  get 'static_pages/liveproduction'
  get 'static_pages/history'
  namespace :api do
    resources :live_data, only: [] do 
      get :display_live_data, on: :collection
      get :history, on: :collection
    end
  end
  # root 'application#hello'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/api/live_data_controller.rb
class Api::LiveDataController < ActionController::API
    def display_live_data
        render json: {	
	        'pv_panel_status': 'functional',
	        'live_data': [
                'pv_cell_temperature': 41,
                'light_intensity':  128,
                'output_power': 425,
                'voltage': 36,
                'yield': 1.10
	        ]
        }
    end

    def history
        render json: {
            'database_data': [
                '21.02.2020': [
                    'max_outout_power': 447,
                    'yield': 1.10,
                    'solar_irradiation': 975,
                    'medium_pv_tempterature': 42,
                ],
                '20.02.2020': [
                    'max_outout_power': 440,
                    'yield': 0.79,
                    'solar_irradiation': 1013,
                    'medium_pv_tempterature': 41,
                ],
                '19.02.2020': [
                    'max_outout_power': 433,
                    'yield': 1.28,
                    'solar_irradiation': 891,
                    'medium_pv_tempterature': 36,
                ],
                '18.02.2020': [
                    'max_outout_power': 443,
                    'yield': 1.16,
                    'solar_irradiation': 929,
                    'medium_pv_tempterature': 39,
                ],
                '17.02.2020': [
                    'max_outout_power': 445,
                    'yield': 0.99,
                    'solar_irradiation': 983,
                    'medium_pv_tempterature': 40,
                ],
                '16.02.2020': [
                    'max_outout_power': 447,
                    'yield': 0.83,
                    'solar_irradiation': 1003,
                    'medium_pv_tempterature': 42,
                ],
                '15.02.2020': [
                    'max_outout_power': 434,
                    'yield': 1.11,
                    'solar_irradiation': 981,
                    'medium_pv_tempterature': 37,
                ],
                '14.02.2020': [
                    'max_outout_power': 442,
                    'yield': 1.15,
                    'solar_irradiation': 956,
                    'medium_pv_tempterature': 38,
                ],
                '13.02.2020': [
                    'max_outout_power': 436,
                    'yield': 0.72,
                    'solar_irradiation': 1067,
                    'medium_pv_tempterature': 43,
                ],
                '12.02.2020': [
                    'max_outout_power': 440,
                    'yield': 1.06,
                    'solar_irradiation': 982,
                    'medium_pv_tempterature': 37,
                ]
	        ]
        }
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end

  def weatherstation
  end

  def liveproduction
  end

  def history
    t = Time.now
    @date = "#{t.day}.#{t.month}.#{t.year}"
    @date_yesterday = "#{t.day - 1}.#{t.month}.#{t.year}"
    @date_2_days_ago = "#{t.day - 2}.#{t.month}.#{t.year}"
    @date_3_days_ago = "#{t.day - 3}.#{t.month}.#{t.year}"
    @date_4_days_ago = "#{t.day - 4}.#{t.month}.#{t.year}"
    @date_5_days_ago = "#{t.day - 5}.#{t.month}.#{t.year}"
    @date_6_days_ago = "#{t.day - 6}.#{t.month}.#{t.year}"
    @date_7_days_ago = "#{t.day - 7}.#{t.month}.#{t.year}"
    @date_8_days_ago = "#{t.day - 8}.#{t.month}.#{t.year}"
    @date_9_days_ago = "#{t.day - 9}.#{t.month}.#{t.year}"
  end
  
  helper_method :history

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PVDataStorage
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    #topheader
      %header.navbar.navbar-fixed-top.navbar-inverse{:style => "background-color: #4285F4;"}
        .container
          .nav
            %ul.nav.navbar-nav
              %li.nav-item
                %a.navbar-brand{:href => "https://mecanica.utcluj.ro/", :type => "button", target: '_blank'}
                  %img.img-responsive.logo{:src => "https://old.utcluj.ro/download/id/SIMBOLURI/01-sigla/JPG/Romana/Varianta%202_negru.jpg", :height => "145", :width => "145"}
              %li{class: action_name == 'about' ? 'active' : ''}
                = link_to "About", static_pages_about_path
              %li{class: action_name == 'weatherstation' ? 'active' : ''}
                = link_to "Weather Station", static_pages_weatherstation_path
              %li{class: action_name == 'liveproduction' ? 'active' : ''}
                = link_to 'Live Performance', static_pages_liveproduction_path
              %li{class: action_name == 'history' ? 'active' : ''}
                = link_to 'History', static_pages_history_path
    %body
= yield

app/views/static_pages/about.html.haml
.body
  %section.cd-intro
    %h1.cd-headline.rotate-1
      %span Despre acest proiect, panouri fotovoltaice și energia produsă
.content
  %h3{:style => "text-align:center"}
    = "Această aplicație are la bază lucrarea 'New approaches in online evaluation of photovoltaic systems efficiency by implementing IoT monitoring solutions' realizată de către:"
  %ul.nav.flex-column
    %li.nav-item{:style => "text-align:center"}
      %a.nav-link.active{:href => "https://mdm.utcluj.ro/colectiv/lecturer-calin-rusu-phd-eng/", target: '_blank',} Călin Rusu
    %li.nav-item{:style => "text-align:center"}
      %a.nav-link.active{:href => "https://mdm.utcluj.ro/colectiv/lecturer-sorin-besoiu-phd-eng/", target: '_blank'} Sorin Besoiu
    %li.nav-item{:style => "text-align:center"}
      %a.nav-link.active{:href => "https://www.linkedin.com/in/lorand-kacso-vidrean-143595109/", target: '_blank'} Lorand Kacso-Vidrean
    %li.nav-item{:style => "text-align:center"}
      %a.nav-link.active{:href => "https://mdm.utcluj.ro/colectiv/lecturer-ciprian-lapusan-phd-eng/", target: '_blank'} Ciprian Lăpușan
  %h3{:align => "left"}
    = "Ceea ce veți vedea în acestă a aplicație, reprezintă faza finală a acestui proiect, cea în care toate datele generate de senzorii atașați de panourile fotovoltaice sunt preluate, depozitate, analizate și afisate cu ajutorul unei interfețe web IOT."
  %h3 Există câteva lucruri interesante despre energia solară pe care probabil nu le știați:

  %ul.list-group
    %li.list-group-item Energia solară este cea mai abundentă sursă de energie de pe Pământ.
    %li.list-group-item Costurile panourilor solare au scăzut cu 99% din 1977.
    %li.list-group-item Energia solară este mai ieftină decât combustibilii fosili.
    %li.list-group-item Instalațiile de panouri solare pot dura 40 de ani sau mai mult.
    %li.list-group-item 39% din capacitatea nouă de producție de energie electrică instalată în 2016 a fost solară.
    %li.list-group-item China este, de departe, liderul mondial în domeniul energiei solare.

app/views/static_pages/history.html.haml
.header
  %h1{:style => "color: #4285F4;"} Istoricul datelor de performanță
.content
  %table.table
    %thead.thead-dark
      %tr
        %th{:scope => "col", :style => "text-align:center"} Ziua
        %th{:scope => "col", :style => "text-align:center"} Puterea maximă generată [W]
        %th{:scope => "col", :style => "text-align:center"} Randamentul [kWh]
        %th{:scope => "col", :style => "text-align:center"} Iradierea solară [W/m2]
        %th{:scope => "col", :style => "text-align:center"} Temperatura medie a panoului solar [°C]
    %tbody
      %tr
        %th{:scope => "row", :style => "text-align:center"}= @date
        %td{:style => "text-align:center"} 447
        %td{:style => "text-align:center"} 1.10
        %td{:style => "text-align:center"} 975
        %td{:style => "text-align:center"} 42
      %tr
        %th{:scope => "row", :style => "text-align:center"}= @date_yesterday
        %td{:style => "text-align:center"} 440
        %td{:style => "text-align:center"} 0.79
        %td{:style => "text-align:center"} 1013
        %td{:style => "text-align:center"} 41
      %tr
        %th{:scope => "row", :style => "text-align:center"}= @date_2_days_ago
        %td{:style => "text-align:center"} 433
        %td{:style => "text-align:center"} 1.28
        %td{:style => "text-align:center"} 891
        %td{:style => "text-align:center"} 36
      %tr
        %th{:scope => "row", :style => "text-align:center"}= @date_3_days_ago
        %td{:style => "text-align:center"} 443
        %td{:style => "text-align:center"} 1.16
        %td{:style => "text-align:center"} 929
        %td{:style => "text-align:center"} 39
      %tr
        %th{:scope => "row", :style => "text-align:center"}= @date_4_days_ago
        %td{:style => "text-align:center"} 445 
        %td{:style => "text-align:center"} 0.99
        %td{:style => "text-align:center"} 983
        %td{:style => "text-align:center"} 40
      %tr
        %th{:scope => "row", :style => "text-align:center"}= @date_5_days_ago
        %td{:style => "text-align:center"} 447
        %td{:style => "text-align:center"} 0.83
        %td{:style => "text-align:center"} 1003
        %td{:style => "text-align:center"} 42
      %tr
        %th{:scope => "row", :style => "text-align:center"}= @date_6_days_ago
        %td{:style => "text-align:center"} 434
        %td{:style => "text-align:center"} 1.11
        %td{:style => "text-align:center"} 981
        %td{:style => "text-align:center"} 37
      %tr
        %th{:scope => "row", :style => "text-align:center"}= @date_7_days_ago
        %td{:style => "text-align:center"} 442
        %td{:style => "text-align:center"} 1.15
        %td{:style => "text-align:center"} 956
        %td{:style => "text-align:center"} 38
      %tr
        %th{:scope => "row", :style => "text-align:center"}= @date_8_days_ago
        %td{:style => "text-align:center"} 436
        %td{:style => "text-align:center"} 0.72
        %td{:style => "text-align:center"} 1067
        %td{:style => "text-align:center"} 43
      %tr
        %th{:scope => "row", :style => "text-align:center"}= @date_9_days_ago
        %td{:style => "text-align:center"} 440
        %td{:style => "text-align:center"} 1.06
        %td{:style => "text-align:center"} 982
        %td{:style => "text-align:center"} 37
  .row
    .col-sm-6{:style => "text-align:center"}
      <iframe width="600" height="371" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vR_CmG8jK8pEeQPLVgYECpmMZcasxK6jCLKNT9mLNEzUOAatgydHew_oclTyOs_G5D45BMC92B_-JdO/pubchart?oid=1425424013&amp;format=interactive"></iframe>
    .col-sm-6{:style => "text-align:center"}
      <iframe width="600" height="371" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vR_CmG8jK8pEeQPLVgYECpmMZcasxK6jCLKNT9mLNEzUOAatgydHew_oclTyOs_G5D45BMC92B_-JdO/pubchart?oid=937377840&amp;format=interactive"></iframe>
  .row{:style => "text-align:center"}
    .li
      = link_to 'https://docs.google.com/spreadsheets/d/1z4XXGYRdQRoxiW0p7jh6FVlOAXWMa2OS07QoqxMDcA0/edit#gid=0', target: '_blank', class: 'btn btn-primary' do
        = "Take me to Performance Statistics Google Sheets"
        %i.fa.fa-chevron-right

app/views/static_pages/liveproduction.html.haml
.header
  .jumbotron.jumbotron-fluid{:style => "background-color: #4285F4;"}
    %h1 Monitorizarea live a panourilor fotovoltaice
.content
  !!!
  %html
    %head
      %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
      %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
      %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css", :rel => "stylesheet"}/
      %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}
      %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"}
    %body
      %h1
        %button.Rec
      .container{:style => "text-align:center"}
        %button.btn.btn-info{"data-target" => "#demo1", "data-toggle" => "collapse", :type => "button"} 
          %h4 Temperatura celulei panoului solar
        #demo1.collapse
          %h2
            41 °C
        %button.btn.btn-info{"data-target" => "#demo2", "data-toggle" => "collapse", :type => "button"} 
          %h4 Intensitatea luminii
        #demo2.collapse
          %h2 
            128 kLux
        %button.btn.btn-info{"data-target" => "#demo3", "data-toggle" => "collapse", :type => "button"} 
          %h4 Puterea generată
        #demo3.collapse
          %h2
            425 W
        %button.btn.btn-info{"data-target" => "#demo4", "data-toggle" => "collapse", :type => "button"} 
          %h4 Tensiunea de funcționare
        #demo4.collapse
          %h2
            36 V
        %button.btn.btn-info{"data-target" => "#demo5", "data-toggle" => "collapse", :type => "button"} 
          %h4 Randamentul
        #demo5.collapse
          %h2
            1.10 kWh

app/views/static_pages/weatherstation.html.haml
.header
  %h1
    = "Date climatice"
  .text-center
    %a.btn.btn-default.btn-logo.active{:href => "https://www.google.ro/maps/place/Cluj-Napoca/@46.7833002,23.4764293,11z/data=!3m1!4b1!4m5!3m4!1s0x47490c1f916c0b8b:0xbbc601c331f148b!8m2!3d46.7712101!4d23.6236353", target: '_blank', :type => "button", :style => "text-align:center"}
      %span.glyphicon.glyphicon-globe{"aria-hidden" => "true"}
        Cluj-Napoca
.content
  .grid-container
    .card{:style => "text-align:center"}
      %img.card-img-top{:alt => "...", :src => "https://image.freepik.com/free-photo/temperature-indicating-instrument-snow_23-2147963627.jpg", :height => "100", :width => "100"}/
      .card-body
        %h5.card-title Temperatură
        %p.card-text 4°C
    .card{:style => "text-align:center"}
      %img.card-img-top{:alt => "...", :src => "https://image.freepik.com/free-photo/water-drops-glass_1323-153.jpg", :height => "100", :width => "100"}/
      .card-body
        %h5.card-title Umiditate
        %p.card-text 53%
    .card{:style => "text-align:center"}
      %img.card-img-top{:alt => "...", :src => "https://image.freepik.com/free-photo/side-view-carefree-man-enjoying-freedom-with-arms-outstretched_23-2148182869.jpg", :height => "100", :width => "100"}/
      .card-body
        %h5.card-title Presiune atmosferică
        %p.card-text 1012 hPa
    .card{:style => "text-align:center"}
      %img.card-img-top{:alt => "...", :src => "https://image.freepik.com/free-photo/california-desert-wind-turbines_1426-506.jpg", :height => "100", :width => "100"}/
      .card-body
        %h5.card-title Viteza vântului
        %p.card-text 12 km/h
    .card{:style => "text-align:center"}
      %img.card-img-top{:alt => "...", :src => "https://image.freepik.com/free-photo/fantastic-cloudscape_1232-490.jpg", :height => "100", :width => "100"}/
      .card-body
        %h5.card-title Grad de înnorare
        %p.card-text Cer noros
    .card{:style => "text-align:center"}
      %img.card-img-top{:alt => "...", :src => "https://image.freepik.com/free-photo/red-neon-lines-colorful-laser-light-dark-background_23-2147881223.jpg", :height => "100", :width => "100"}/
      .card-body
        %h5.card-title Indexul de raze ultraviolete
        %p.card-text 2
    .card{:style => "text-align:center"}
      %img.card-img-top{:alt => "...", :src => "https://image.freepik.com/free-photo/3d-hazy-mountain-range-against-sunset-sky_1048-10361.jpg", :height => "100", :width => "100"}/
      .card-body
        %h5.card-title Răsăritul soarelui
        %p.card-text 07:21
    .card{:style => "text-align:center"}
      %img.card-img-top{:alt => "...", :src => "https://image.freepik.com/free-photo/cloudy-sky-sunset-sea_138670-215.jpg", :height => "100", :width => "100"}/
      .card-body
        %h5.card-title Apusul soarelui
        %p.card-text 17:58